### ISSUE TITLE
Add a path manipulation library

### ISSUE THREAD

**Issue by alaviss** [alaviss/nim-sys#1]
Goals:
- A base for all path-based functionalities in the project.
- Stateless, do not depend on the file system (`sys/fs` will be the extension of `sys/path` for that purpose).

Problems:
- Does the relative vs absolute path distinction matter enough to warrant distinct types?
- Does it matter to be able to manipulate POSIX paths on Windows and vice versa?

**Comment by alaviss** [comment]
Depends on #2, we need `NullessString` as a base for path types.

**Comment by alaviss** [comment]
> Does it matter to be able to manipulate POSIX paths on Windows and vice versa?

Since what we are doing is completely lexical, it would be nice to be able to do this, given that POSIX paths are frequently used everywhere (since it is used for URI).

However it is hard to determine a good API strategy for this. Ideas includes:

- Provide `PosixPath` and `WindowsPath` types with a `Path` type that aliases to the one corresponding to the native OS.
- Provide `paths/posix` and `paths/windows`, with `paths` exporting the native version. However the documentation will have to be duplicated, which is a pain.

> Does the relative vs absolute path distinction matter enough to warrant distinct types?

They do matter, but complicate API usage. For example:

- Programs taking arbitrary input (say, parameters: `foo /foo/x.txt ../bar/x.nim`), which might be an absolute path or a relative path, and it's not possible to provide a `toPath()` that dispatches to the right path type on runtime.
- Not all programs/libraries care about "relative" vs "absolute". They might do just fine with either of them. An `AnyPath` typeclass can solve this.

Solutions:

- `Absolute` and `Relative` being a distinct version of `Path` that provide one-way implicit conversion back to `Path`. Converters have to be investigated to see if they are "safe" enough first. Alternatively an `AnyPath` typeclass can provide the same functionality, but we would still need the `Path` type due to the dispatching issue in the first example.
- `Path` being a variant object that might refer to either `Absolute` or `Relative`.

**Comment by alaviss** [comment]
Notes for POSIX implementation:

- `..` is a dangerous atom: `a/../b` is not necessary to be equal to `b`, since if `a` is a symlink, the `..` atom will resolves to the parent of whatever `a` refers to.

**Comment by alaviss** [comment]
Notes for Windows implementation:

- Microsoft documentation on path namespaces: https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file
- It is untested how Windows `..` atom behaves compared to POSIX. Windows do have symbolic links, but they might not carry the surprising behavior of POSIX. This has to be tested however.
- Regular DOS paths (eg. `C:\path\to\something`) contain plenty of surprising behaviors:
  - Certain names are "special" (refer to the linked doc for more information): `C:\Windows\System32\NUL` is the same as `NUL`, `NUL.txt` is the same as `NUL`, but `NULabcd` is not special. Not sure if `NUL` being a directory will work (ie. `C:\NUL\a.txt`), but it's safe to assume that it is not.
  - There is a limitation of 260 characters.
  - Trailing space (` `, untested if all form of spaces or just the space character) or period `.` in each path element are trimmed automagically by the Windows API. This means `C:\Windows.\System32` is the same as `C:\Windows\System32`.
  - `/` is a valid path separator and will be treated in the same way as `\` (only if `/` is used exclusively?).
  - `C:Windows` is not the same as `C:\Windows`. The former is a relative path.
  - `\something` is a relative path.
- It is unknown how much of DOS path issues applies to UNC paths (eg. `\\hostname`).
- Device paths (paths starting with `\\?` or `\\.`) does not share the limitations of DOS paths.

**Comment by alaviss** [comment]
Differs in path semantics between Windows and POSIX makes it hard to determine the characteristic of the `Path` type. It is unsure if a `Path` type should be formed or if string-based (to be more precise, `strings.Nulless`-based) interface should be used instead.

**Comment by barcharcraz** [comment]
For what it's worth we managed to support both kinds of windows paths in c++'s std::filesystem::path interface at the same time. (NT paths and Windows paths)
