### ISSUE TITLE
Add a sockets library

### ISSUE THREAD

**Issue by alaviss** [alaviss/nim-sys#22]
Now that `sys` hosts one of the only OS-agnostic async implementation based on CPS, there is a lot of demand for a socket library.

An unordered list of things to do:
- A generic `Socket` type that works with all sockets.
  - Use the same `read()`, `write()` interface as with `files`. This should allow concepts and friends to match sockets as well as files.
- Specialized distinct `TCPSocket` or even `TCPClient` types to specialize sockets into different kinds, then implement specialized operations on top.
- Figure out the best way to handle dual-stack sockets and whether they should be the default. Some operating systems like OpenBSD and Dragonfly does not support dual-stack.
- Figure out how timeout should be done. For synchronized sockets this should be very simple, the question lies on async sockets.

Open questions:
- What to do with DNS resolution? On the majority of OS this is fully synchronous and we don't have thread migration support at the moment. Might have to look into [`loony`](https://github.com/nim-works/loony), but it doesn't work with ORC.

A lot more research has to be done as the topic is researched further

**Comment by disruptek** [comment]
Don't worry about DNS; it's practically the perfect use-case for the cubby concept, so we'll have an impl Real Soon Now.
